apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server
  labels:
    app: edge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-server
  template:
    metadata:
      labels:
        app: edge-server
      annotations:
        # 就这一行！Operator 看到它，会注入 javaagent 工作
        instrumentation.opentelemetry.io/inject-java: "java-instrumentation"
    spec:
      containers:
        - name: edge-server
          image: edge-server-8:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            #            - name: BPL_JVM_THREAD_COUNT
            #              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service
            - name: ORDER_SERVICE_URL
              value: http://order-service
            - name: DATA_REDIS_HOST
              value: polar-redis

                # service.name 告诉 OTEL 这个服务叫什么名字
                # 在 Jaeger 里你会看到 "edge-server" 这个标签

            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_SERVICE_NAME
              value: "edge-server"
                # 建议同时注入 K8s 的 Pod 和 Namespace 信息作为 Resource Attribute
                # 这样在 Jaeger 里排查问题时，你能直接看到是哪个 Pod 产生的 Trace


            # 1. 先用 Downward API 获取本 pod 的信息
            # springboot 中可以直接获取 @Value("${POD_NAME}")
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # 2. 组装给 OTEL Java 探针使用
            # 探针看到这个变量后，发出去的每一条 tracing 都会自动带上这些标签
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE)"
            # 3. 告诉探针 Collector 在哪里
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring:4318"



---

apiVersion: v1
kind: Service
metadata:
  name: edge-server
  labels:
    app: edge-server
spec:
  type: ClusterIP
  selector:
    app: edge-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000