apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server
  labels:
    app: edge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-server
  template:
    metadata:
      labels:
        app: edge-server
      annotations:
        # 就这一行！Operator 看到它，会自动完成所有 Agent 注入工作
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: edge-server
          image: edge-server-8:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            #            - name: BPL_JVM_THREAD_COUNT
            #              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service
            - name: ORDER_SERVICE_URL
              value: http://order-service
            - name: DATA_REDIS_HOST
              value: polar-redis

                # service.name 告诉 OTEL 这个服务叫什么名字
                # 在 Jaeger 里你会看到 "edge-server" 这个标签

            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_SERVICE_NAME
              value: "edge-server"
                # 建议同时注入 K8s 的 Pod 和 Namespace 信息作为 Resource Attribute
                # 这样在 Jaeger 里排查问题时，你能直接看到是哪个 Pod 产生的 Trace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.namespace.name=$(NAMESPACE),k8s.pod.name=$(POD_NAME)"

            # 以下两个环境变量用于上面的 valueFrom
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name



---

apiVersion: v1
kind: Service
metadata:
  name: edge-server
  labels:
    app: edge-server
spec:
  type: ClusterIP
  selector:
    app: edge-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000