apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: production-proxy-config
  namespace: default
spec:
  telemetry:
    tracing:
      samplingRate: 100        # 采样率，0-100，百分比
      provider:
        backendRefs:
          - name: otel-collector
            namespace: default
            port: 4317
        type: OpenTelemetry
      customTags:              # 自定义 Span attributes（后面专门讲）
        provider:
          type: Literal
          literal:
            value: "production"
        sender:
          type: Literal
          literal:
            value: "李兰兰"
        polar.tenant.id:
          type: RequestHeader
          requestHeader:
            name: X-Tenant-ID
            defaultValue: "UNKNOWN"

        k8s.pod.name:
          type: Environment
          environment:
            name: POD_NAME
            defaultValue: "UNKNOWN"

    accessLog:
      disable: false   # 一键控制是否启用 access logging
      settings:
        - sinks:
            - type: OpenTelemetry
              openTelemetry:
                backendRefs:
                  - name: otel-collector
                    namespace: default
                    port: 4317
                resourceAttributes:
                  k8s.cluster.name: "sg-kind-cluster-01"
                  gateway.name: "main-ingress-gateway"
                  service.name: "envoy-gateway"
            - type: File
              file:
                path: /dev/stdout
#          matches:
#            - "'x-envoy-logged' in request.headers"  # header 中必须有这个 key 的才 log
          format:
            type: JSON
            json:
              # request 相关
              trace_id: "%REQ(TRACEPARENT)%"  # 提取 W3C Trace 头
              request_id: "%REQ(X-REQUEST-ID)%"

              method: "%REQ(:METHOD)%"
              path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              x-forworded-for: "%REQ(X-FORWARDED-FOR)%"
              user-agent: "%REQ(USER-AGENT)%"
              protocol: "%PROTOCOL%"

              # upstream 相关

              "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
              "upstream_host": "%UPSTREAM_HOST%"
              "upstream_cluster": "%UPSTREAM_CLUSTER%"
              "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%"

              # 下游 相关
              downstream_ip: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
              "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%"
              "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%"
              "requested_server_name": "%REQUESTED_SERVER_NAME%"
              "route_name": "%ROUTE_NAME%"

              # response 相关
              response_code: "%RESPONSE_CODE%"
              response_flags: "%RESPONSE_FLAGS%" # 黄金排错兵器
              "response_code_details": "%RESPONSE_CODE_DETAILS%"

              # time 相关
              timestamp: "%START_TIME%"
              duration_ms: "%DURATION%"

              "x-envoy-upstream-service-time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"