custom_build(
    # container name
    ref='order-service',
    # command to build image
    command='./gradlew jibDockerBuild -PimageName=$EXPECTED_REF',
    # Files to watch that trigger a new build
    deps=['build.gradle', 'settings.gradle', 'gradle.properties', 'src'],
    # For resource-only changes, sync files directly into the running container
    # instead of rebuilding the full image.
    live_update=[
        sync('src/main/resources', '/app/resources'),
        run('sh -c "touch /app/resources/.reloadtrigger"')
    ]
)

# Deployment
k8s_yaml(['k8s/deployment.yaml'])

# Manage
k8s_resource(
    'order-service',
    port_forwards=['9002:9002'],
    trigger_mode=TRIGGER_MODE_MANUAL
)
